/*  COMO NÃO TEM OUTROS BOTÕES PARA O OBSERVA PE, ESTE CÓDIGO NÃO ESTÁ SENDO USADO POR ENQUANTO,
    MAS JÁ ESTÁ PRONTO COM A ROTA CONFIGURADA E COMENTADA NO ARQUIVO ROUTER.JSX PARA IMPLEMENTAÇÕES FUTURAS
*/

export default function ObservaPE() {
  return (
    <>
      <div>teste</div>
    </>
  );
}
